spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms-shema
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  graphql:
    schema:
      printer:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
graphql:
  servlet:
    exception-handlers-enabled: true
    mapping: /graphql
    enabled: true
    cors-enabled: false
